### Route GET api /articles

GET http://localhost:3000/v1/articles


### Route GET api /articles/{id}

GET http://localhost:3000/v1/articles/1


### Route GET /profil/:id (profil Abram id4)
GET  http://localhost:3000/v1/profil/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJhemVydHlAZ21haWwuY29tIiwicHNldWRvIjoiQnJhbXM3NSIsImludGVydmFsX2RhdGUiOnsibWludXRlcyI6Mywic2Vjb25kcyI6NDIsIm1pbGxpc2Vjb25kcyI6Mjk3LjkyNH0sImxldmVsX2lkIjozLCJpbWciOiJodHRwczovL2ltYWdlcy5wZXhlbHMuY29tL3Bob3Rvcy80MTA3MjgyL3BleGVscy1waG90by00MTA3MjgyLmpwZWc_YXV0bz1jb21wcmVzcyZjcz10aW55c3JnYiZkcHI9MiZoPTc1MCZ3PTEyNjAiLCJmaXJzdE5hbWUiOiJBYnJhbSIsImxhc3ROYW1lIjoiUG9tcG9zZWxsaSIsImlhdCI6MTYxNTk5MDQ1M30.7hRAx5UdRxc-0-3VWQHx5Pjc2TsFjlhIHnH39gjynnU


### Route POST api /registration (profil Abram id4)

POST http://localhost:3000/v1/registration
Content-Type: application/json

{
    "email": "azerty@gmail.com",
    "password": "oklm",
    "firstName": "Abram",
    "lastName": "Pomposelli",
    "pseudo": "Brams75",
    "img": "https://images.pexels.com/photos/4107282/pexels-photo-41072"
}


### Route POST api /login (user abram id4)
POST http://localhost:3000/v1/login
Content-Type: application/json

{
   
    "email": "azertyy@gmail.com",
    "password": "oklm"
}


### Route GET api /questions/:id (user Abram id4)

GET http://localhost:3000/v1/questions/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJhemVydHlAZ21haWwuY29tIiwicHNldWRvIjoiQnJhbXM3NSIsImludGVydmFsX2RhdGUiOnsibWludXRlcyI6Mywic2Vjb25kcyI6NDIsIm1pbGxpc2Vjb25kcyI6Mjk3LjkyNH0sImxldmVsX2lkIjozLCJpbWciOiJodHRwczovL2ltYWdlcy5wZXhlbHMuY29tL3Bob3Rvcy80MTA3MjgyL3BleGVscy1waG90by00MTA3MjgyLmpwZWc_YXV0bz1jb21wcmVzcyZjcz10aW55c3JnYiZkcHI9MiZoPTc1MCZ3PTEyNjAiLCJmaXJzdE5hbWUiOiJBYnJhbSIsImxhc3ROYW1lIjoiUG9tcG9zZWxsaSIsImlhdCI6MTYxNTk5MDQ1M30.7hRAx5UdRxc-0-3VWQHx5Pjc2TsFjlhIHnH39gjynnU


### Route POST api/questions/:id (user Abram id4)

POST http://localhost:3000/v1/questions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJhemVydHlAZ21haWwuY29tIiwicHNldWRvIjoiQnJhbXM3NSIsImludGVydmFsX2RhdGUiOnsibWludXRlcyI6Mywic2Vjb25kcyI6NDIsIm1pbGxpc2Vjb25kcyI6Mjk3LjkyNH0sImxldmVsX2lkIjozLCJpbWciOiJodHRwczovL2ltYWdlcy5wZXhlbHMuY29tL3Bob3Rvcy80MTA3MjgyL3BleGVscy1waG90by00MTA3MjgyLmpwZWc_YXV0bz1jb21wcmVzcyZjcz10aW55c3JnYiZkcHI9MiZoPTc1MCZ3PTEyNjAiLCJmaXJzdE5hbWUiOiJBYnJhbSIsImxhc3ROYW1lIjoiUG9tcG9zZWxsaSIsImlhdCI6MTYxNTk5MDQ1M30.7hRAx5UdRxc-0-3VWQHx5Pjc2TsFjlhIHnH39gjynnU
Content-Type: application/json

{
    "level_id": 3
}


### Route GET api /challenges (user Abram id4)

GET http://localhost:3000/v1/challenges
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJhemVydHlAZ21haWwuY29tIiwicHNldWRvIjoiQnJhbXM3NSIsImludGVydmFsX2RhdGUiOnsibWludXRlcyI6Mywic2Vjb25kcyI6NDIsIm1pbGxpc2Vjb25kcyI6Mjk3LjkyNH0sImxldmVsX2lkIjozLCJpbWciOiJodHRwczovL2ltYWdlcy5wZXhlbHMuY29tL3Bob3Rvcy80MTA3MjgyL3BleGVscy1waG90by00MTA3MjgyLmpwZWc_YXV0bz1jb21wcmVzcyZjcz10aW55c3JnYiZkcHI9MiZoPTc1MCZ3PTEyNjAiLCJmaXJzdE5hbWUiOiJBYnJhbSIsImxhc3ROYW1lIjoiUG9tcG9zZWxsaSIsImlhdCI6MTYxNTk5MDQ1M30.7hRAx5UdRxc-0-3VWQHx5Pjc2TsFjlhIHnH39gjynnU


### Route GET api /challenges/:id (user Abram id4)

GET http://localhost:3000/v1/challenges/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJhemVydHlAZ21haWwuY29tIiwicHNldWRvIjoiQnJhbXM3NSIsImludGVydmFsX2RhdGUiOnsibWludXRlcyI6Mywic2Vjb25kcyI6NDIsIm1pbGxpc2Vjb25kcyI6Mjk3LjkyNH0sImxldmVsX2lkIjozLCJpbWciOiJodHRwczovL2ltYWdlcy5wZXhlbHMuY29tL3Bob3Rvcy80MTA3MjgyL3BleGVscy1waG90by00MTA3MjgyLmpwZWc_YXV0bz1jb21wcmVzcyZjcz10aW55c3JnYiZkcHI9MiZoPTc1MCZ3PTEyNjAiLCJmaXJzdE5hbWUiOiJBYnJhbSIsImxhc3ROYW1lIjoiUG9tcG9zZWxsaSIsImlhdCI6MTYxNTk5MDQ1M30.7hRAx5UdRxc-0-3VWQHx5Pjc2TsFjlhIHnH39gjynnU


### Route PATCH api /settings/profil/:id (user Abram id4)

PATCH http://localhost:3000/v1/settings/profil/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJhemVydHlAZ21haWwuY29tIiwicHNldWRvIjoiQnJhbXM3NSIsImludGVydmFsX2RhdGUiOnsibWludXRlcyI6Mywic2Vjb25kcyI6NDIsIm1pbGxpc2Vjb25kcyI6Mjk3LjkyNH0sImxldmVsX2lkIjozLCJpbWciOiJodHRwczovL2ltYWdlcy5wZXhlbHMuY29tL3Bob3Rvcy80MTA3MjgyL3BleGVscy1waG90by00MTA3MjgyLmpwZWc_YXV0bz1jb21wcmVzcyZjcz10aW55c3JnYiZkcHI9MiZoPTc1MCZ3PTEyNjAiLCJmaXJzdE5hbWUiOiJBYnJhbSIsImxhc3ROYW1lIjoiUG9tcG9zZWxsaSIsImlhdCI6MTYxNTk5MDQ1M30.7hRAx5UdRxc-0-3VWQHx5Pjc2TsFjlhIHnH39gjynnU
Content-Type: application/json

{
    "email": "azerty@gmail.com",
    "password": "oklm",
    "firstName": "Abramss",
    "lastName": "Pomposselli",
    "pseudo": "Brams75",
    "img": "https://images.pexels.com/photos/4107282/pexels-photo-41072"
}




