
### Route GET api /articles

GET http://localhost:3000/v1/articles


### Route GET api /articles/{id}

GET http://localhost:3000/v1/articles/1


### Route GET /profil/:id (profil 6)
GET  http://localhost:3000/v1/profil/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJ0ZXN0MUBnbWFpbC5jb20iLCJwc2V1ZG8iOiJUZXN0ZTEiLCJkYXRlIjoiMjAyMS0wMy0xNlQwOTo0NzoxOC41ODJaIiwiaWF0IjoxNjE1ODg2MTIwfQ.3Z6zvYDxFCycdO242wvxmidLYQgHWU9fcsx75EgxIWw


### Route POST api /registration (profil 6)

POST http://localhost:3000/v1/registration
Content-Type: application/json

{
    "email": "test3@gmail.com",
    "password": "untest",
    "firstName": "Test3",
    "lastName": "Test3",
    "pseudo": "Teste3",
    "img": "https://www.pexels.com/fr-fr/photo/bouteilles-en-verre-dans-un-sac-3735218/",
    "date": "2021-03-16 10:47:18.582511+01"
}


### Route POST api /login (user 18)
POST http://localhost:3000/v1/login
Content-Type: application/json

{
   
  "email": "test3@gmail.com",
"password": "untest"
}


### Route GET api /questions/:id (user 6)

GET http://localhost:3000/v1/questions/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJ0ZXN0MUBnbWFpbC5jb20iLCJwc2V1ZG8iOiJUZXN0ZTEiLCJkYXRlIjoiMjAyMS0wMy0xNlQwOTo0NzoxOC41ODJaIiwiaWF0IjoxNjE1ODg2MTIwfQ.3Z6zvYDxFCycdO242wvxmidLYQgHWU9fcsx75EgxIWw


### Route POST api/questions/:id (user 6)

POST http://localhost:3000/v1/questions/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJ0ZXN0MUBnbWFpbC5jb20iLCJwc2V1ZG8iOiJUZXN0ZTEiLCJkYXRlIjoiMjAyMS0wMy0xNlQwOTo0NzoxOC41ODJaIiwiaWF0IjoxNjE1ODg2MTIwfQ.3Z6zvYDxFCycdO242wvxmidLYQgHWU9fcsx75EgxIWw
Content-Type: application/json

{
    "level_id": 2
}


### Route GET api /challenges (user 6)

GET http://localhost:3000/v1/challenges
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJ0ZXN0MUBnbWFpbC5jb20iLCJwc2V1ZG8iOiJUZXN0ZTEiLCJkYXRlIjoiMjAyMS0wMy0xNlQwOTo0NzoxOC41ODJaIiwiaWF0IjoxNjE1ODg2MTIwfQ.3Z6zvYDxFCycdO242wvxmidLYQgHWU9fcsx75EgxIWw


### Route GET api /challenges/:id (user 6)

GET http://localhost:3000/v1/challenges/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJ0ZXN0MUBnbWFpbC5jb20iLCJwc2V1ZG8iOiJUZXN0ZTEiLCJkYXRlIjoiMjAyMS0wMy0xNlQwOTo0NzoxOC41ODJaIiwiaWF0IjoxNjE1ODg2MTIwfQ.3Z6zvYDxFCycdO242wvxmidLYQgHWU9fcsx75EgxIWw


### Route PATCH api /settings/profil/:id (user 18)
PATCH http://localhost:3000/v1/settings/profil/18
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgsImVtYWlsIjoidGVzdDNAZ21haWwuY29tIiwicHNldWRvIjoiVGVzdGUzIiwiZGF0ZSI6IjIwMjEtMDMtMTZUMDk6NDc6MTguNTgyWiIsImlhdCI6MTYxNTk4NzE0NX0.msGMtIZzHcff6tfvSPHl-fSqRaTOsaZOx-u3nKh9siI
Content-Type: application/json

{
    "email": "test3@gmail.com",
    "password": "untest",
    "firstName": "Test3",
    "lastName": "Modif",
    "pseudo": "Modif1",
    "img": "https://www.pexels.com/fr-fr/photo/bouteilles-en-verre-dans-un-sac-3735218/",
    "date": "2021-03-16 10:47:18.582511+01"
}


## 2ème user

### Route POST api /registration (profil 6)

POST http://localhost:3000/v1/registration
Content-Type: application/json

{
    "email": "test2@gmail.com",
    "password": "testdeux",
    "firstName": "Test2",
    "lastName": "Test2",
    "pseudo": "Teste2",
    "img": "https://www.pexels.com/fr-fr/photo/bouteilles-en-verre-dans-un-sac-3735218/",
    "date": "2021-03-16 10:47:18.582511+01"
}

### Route POST api /login (user 8)
POST http://localhost:3000/v1/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiJ0ZXN0MkBnbWFpbC5jb20iLCJwc2V1ZG8iOiJUZXN0ZTIiLCJkYXRlIjoiMjAyMS0wMy0xNlQwOTo0NzoxOC41ODJaIiwiaWF0IjoxNjE1ODk4NzE3fQ.lQuNZf1ya23IaNst4KjHZrTpn2vmAFvmXwc5dBKjHMU

Content-Type: application/json

{
   
   "email": "test2@gmail.com",
    "password": "testdeux"
}


### Route PATCH api /settings/profil/:id (user 8)
PATCH http://localhost:3000/v1/settings/profil/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiJ0ZXN0MkBnbWFpbC5jb20iLCJwc2V1ZG8iOiJUZXN0ZTIiLCJkYXRlIjoiMjAyMS0wMy0xNlQwOTo0NzoxOC41ODJaIiwiaWF0IjoxNjE1ODk4NzE3fQ.lQuNZf1ya23IaNst4KjHZrTpn2vmAFvmXwc5dBKjHMU

Content-Type: application/json

{
    "email": "test2@gmail.com",
    "password": "testdeux",
    "firstName": "Test2modify",
    "lastName": "Test2modify",
    "pseudo": "Teste2",
    "img": "https://www.pexels.com/fr-fr/photo/bouteilles-en-verre-dans-un-sac-3735218/",
    "date": "2021-03-16 10:47:18.582511+01"
}