
### Route GET heroku /articles

GET https://kodo-ecolo.herokuapp.com/v1/articles

### Route GET api /articles

GET http://localhost:3000/v1/articles


### Route GET heroku /articles/{id}

GET https://kodo-ecolo.herokuapp.com/v1/articles/10


### Route GET api /articles/{id}

GET http://localhost:3000/v1/articles/1


### Route POST heroku /registration (profil 163)

POST https://kodo-ecolo.herokuapp.com/v1/registration
Content-Type: application/json

{
    "email": "matiuyo2456@gmail.com",
    "password": "fezifjieazefeeoiei",
    "firstName": "Mat",
    "lastName": "matthieu",
    "pseudo": "Matre226",
    "img": "https://www.pexels.com/fr-fr/photo/bouteilles-en-verre-dans-un-sac-3735218/",
    "date": "2021-03-05 21:47:18.582511+01"
}


### Route POST heroku /login (profil 163)

POST https://kodo-ecolo.herokuapp.com/v1/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYzLCJlbWFpbCI6Im1hdGl1eW8yNDU2QGdtYWlsLmNvbSIsInBzZXVkbyI6Ik1hdHJlMjI2IiwiZGF0ZSI6IjIwMjEtMDMtMDVUMjA6NDc6MTguNTgyWiIsImlhdCI6MTYxNTUzODMyOH0.JYR1r-L5_OYq0mMD6Gj4HyyiynCSMhKm-yCJBre-jOQ

Content-Type: application/json

{
    "email": "matiuyo2456@gmail.com",
    "password": "fezifjieazefeeoiei"
}


### Route POST api /registration (profil 160)

POST http://localhost:3000/v1/registration
Content-Type: application/json

{
    "email": "audrey234@gmail.com",
    "password": "ghuihguh",
    "firstName": "Alexandre",
    "lastName": "Audrey",
    "pseudo": "Audy234",
    "img": "https://www.pexels.com/fr-fr/photo/bouteilles-en-verre-dans-un-sac-3735218/",
    "date": "2021-03-04 21:47:18.582511+01"
}


### Route POST api /login (profil 160)

POST http://localhost:3000/v1/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTY1LCJlbWFpbCI6ImF1ZHJleTIzNEBnbWFpbC5jb20iLCJwc2V1ZG8iOiJBdWR5MjM0IiwiZGF0ZSI6IjIwMjEtMDMtMDRUMjA6NDc6MTguNTgyWiIsImlhdCI6MTYxNTUzODUyNX0.lH9oGIQr0lBgRcuiI4KKYSVGT4Bu0SOP8RiYNVn_vME

Content-Type: application/json

{
   
    "email": "audrey234@gmail.com",
    "password": "ghuihguh"
}


### Route GET heroku /profil/:id

GET https://kodo-ecolo.herokuapp.com/v1/profil/163
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYzLCJlbWFpbCI6Im1hdGl1eW8yNDU2QGdtYWlsLmNvbSIsInBzZXVkbyI6Ik1hdHJlMjI2IiwiZGF0ZSI6IjIwMjEtMDMtMDVUMjA6NDc6MTguNTgyWiIsImlhdCI6MTYxNTUzODMyOH0.JYR1r-L5_OYq0mMD6Gj4HyyiynCSMhKm-yCJBre-jOQ


### Route GET api /profil/:id

GET http://localhost:3000/v1/profil/160
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJtYXRpdXlvQGdtYWlsLmNvbSIsInBzZXVkbyI6Ik1hdHJlIiwiaWF0IjoxNjE1NDU4ODU3fQ.IjAaiczfKlPVRLe80RkQ-4ML859eqRH59xLavbA2rYo


### Route PATCH heroku /settings/profil/:id 
PATCH https://kodo-ecolo.herokuapp.com/v1/settings/profil/163
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYzLCJlbWFpbCI6Im1hdGl1eW8yNDU2QGdtYWlsLmNvbSIsInBzZXVkbyI6Ik1hdHJlMjI2IiwiZGF0ZSI6IjIwMjEtMDMtMDVUMjA6NDc6MTguNTgyWiIsImlhdCI6MTYxNTUzODMyOH0.JYR1r-L5_OYq0mMD6Gj4HyyiynCSMhKm-yCJBre-jOQ

Content-Type: application/json

{
     "email": "matiuyo2456@gmail.com",
    "password": "fezifjieazefeeoiei",
    "firstName": "Mat",
    "lastName": "maurice",
    "pseudo": "Matre226",
    "img": "https://www.pexels.com/fr-fr/photo/bouteilles-en-verre-dans-un-sac-3735218/",
    "date": "2021-03-05 21:47:18.582511+01"
}

### Route PATCH api /settings/profil/:id

PATCH http://localhost:3000/v1/settings/profil/160
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJtYXRpdXlvQGdtYWlsLmNvbSIsInBzZXVkbyI6Ik1hdHJlIiwiaWF0IjoxNjE1NDU4ODU3fQ.IjAaiczfKlPVRLe80RkQ-4ML859eqRH59xLavbA2rYo

Content-Type: application/json

{
    "email": "audrey1234@gmail.com",
    "password": "ghuihguh",
    "firstName": "Alexandre",
    "lastName": "Amélie",
    "pseudo": "Audy1234",
    "img": "https://www.pexels.com/fr-fr/photo/bouteilles-en-verre-dans-un-sac-3735218/",
    "date": "2021-03-04 21:47:18.582511+01"
}


### Route GET heroku /questions/:id (user 163)

GET https://kodo-ecolo.herokuapp.com/v1/questions/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYzLCJlbWFpbCI6Im1hdGl1eW8yNDU2QGdtYWlsLmNvbSIsInBzZXVkbyI6Ik1hdHJlMjI2IiwiZGF0ZSI6IjIwMjEtMDMtMDVUMjA6NDc6MTguNTgyWiIsImlhdCI6MTYxNTUzODMyOH0.JYR1r-L5_OYq0mMD6Gj4HyyiynCSMhKm-yCJBre-jOQ


### Route GET api /questions/:id (user 160)

GET http://localhost:3000/v1/questions/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJtYXRpdXlvQGdtYWlsLmNvbSIsInBzZXVkbyI6Ik1hdHJlIiwiaWF0IjoxNjE1NDU4ODU3fQ.IjAaiczfKlPVRLe80RkQ-4ML859eqRH59xLavbA2rYo


### Route POST heroku /questions/:id (user 163)
POST https://kodo-ecolo.herokuapp.com/v1/questions/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYzLCJlbWFpbCI6Im1hdGl1eW8yNDU2QGdtYWlsLmNvbSIsInBzZXVkbyI6Ik1hdHJlMjI2IiwiZGF0ZSI6IjIwMjEtMDMtMDVUMjA6NDc6MTguNTgyWiIsImlhdCI6MTYxNTUzODMyOH0.JYR1r-L5_OYq0mMD6Gj4HyyiynCSMhKm-yCJBre-jOQ

Content-Type: application/json

{
    "statement": "Q1 Lorsque vous quittez une pièce, la lumière, vous :",
    "answer_id": 3
}

### Route POST api/questions/:id (user 160)

POST http://localhost:3000/v1/questions/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJtYXRpdXlvQGdtYWlsLmNvbSIsInBzZXVkbyI6Ik1hdHJlIiwiaWF0IjoxNjE1NDU4ODU3fQ.IjAaiczfKlPVRLe80RkQ-4ML859eqRH59xLavbA2rYo

Content-Type: application/json

{
    "statement": "Q2 Qu''y a t-il dans votre dressing ?",
    "answer_id": 5
}


### Route GET heroku /challenges (user 163)

GET https://kodo-ecolo.herokuapp.com/v1/challenges
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYzLCJlbWFpbCI6Im1hdGl1eW8yNDU2QGdtYWlsLmNvbSIsInBzZXVkbyI6Ik1hdHJlMjI2IiwiZGF0ZSI6IjIwMjEtMDMtMDVUMjA6NDc6MTguNTgyWiIsImlhdCI6MTYxNTUzODMyOH0.JYR1r-L5_OYq0mMD6Gj4HyyiynCSMhKm-yCJBre-jOQ


### Route GET api /challenges (user 160)

GET http://localhost:3000/v1/challenges
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJtYXRpdXlvQGdtYWlsLmNvbSIsInBzZXVkbyI6Ik1hdHJlIiwiaWF0IjoxNjE1NDU4ODU3fQ.IjAaiczfKlPVRLe80RkQ-4ML859eqRH59xLavbA2rYo


### Route GET heroku /challenges/:id (user 163)

GET https://kodo-ecolo.herokuapp.com/v1/challenges/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYzLCJlbWFpbCI6Im1hdGl1eW8yNDU2QGdtYWlsLmNvbSIsInBzZXVkbyI6Ik1hdHJlMjI2IiwiZGF0ZSI6IjIwMjEtMDMtMDVUMjA6NDc6MTguNTgyWiIsImlhdCI6MTYxNTUzODMyOH0.JYR1r-L5_OYq0mMD6Gj4HyyiynCSMhKm-yCJBre-jOQ


### Route GET api /challenges/:id (user 160)

GET http://localhost:3000/v1/challenges/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJtYXRpdXlvQGdtYWlsLmNvbSIsInBzZXVkbyI6Ik1hdHJlIiwiaWF0IjoxNjE1NDU4ODU3fQ.IjAaiczfKlPVRLe80RkQ-4ML859eqRH59xLavbA2rYo



